# Generated by Django 5.0.6 on 2024-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0002_lotteryentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LotteryEntry",
        ),
    ]
