# Generated by Django 5.0.6 on 2024-07-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0005_lotterywinning"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LotteryWinning",
        ),
    ]
